import type { Metadata } from "next";
import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry';
import Header from '@/components/Dashboard/Header/Header'
import { Box } from "@mui/material";
import scss from './Layout.module.scss';

export const metadata: Metadata = {
  title: "GetComms",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <body>
        <ThemeRegistry >
          <Header />
          <Box className={scss.main}>
            {children}
          </Box>
        </ThemeRegistry>
      </body>
    </html>
  );
};

export default RootLayout;
