name: Deploy to Azure App Service using Docker Hub

on:
  push:
    branches:
      - feature/api/dockerizing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Iniciar sesión en Docker Hub
    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Construir y hacer push de la imagen del API de NestJS a Docker Hub
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push API
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Fulltimeforce.GetComms.API/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/project-getcomms-api:latest

    - name: Build and push UI
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Fulltimeforce.GetComms.UI/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/project-getcomms-ui:latest

    # Desplegar en Azure App Service el API
    - name: Deploy API to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'project-getcomms-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        images: 'stephgl/project-getcomms-api:latest'
        
    # Desplegar en Azure App Service la UI
    - name: Deploy UI to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'project-getcomms-ui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_UI }}
        images: 'stephgl/project-getcomms-ui:latest'
