name: Deploy to Azure App Service using Docker Hub

on:
  push:
    branches:
      - feature/api/dockerizing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Iniciar sesión en Docker Hub
    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Construir y hacer push de la imagen del API de NestJS a Docker Hub
    - name: Build and push NestJS API image to Docker Hub
      run: |
        docker build -t stephgl/project-getcomms-api:latest ./Fulltimeforce.GetComms.API
        docker push stephgl/project-getcomms-api:latest

    # Construir y hacer push de la imagen de la UI de Next.js a Docker Hub
    - name: Build and push Next.js UI image to Docker Hub
      run: |
        docker build -t stephgl/project-getcomms-ui:latest ./Fulltimeforce.GetComms.UI
        docker push stephgl/project-getcomms-ui:latest

    # Desplegar en Azure App Service el API
    - name: Deploy API to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'project-getcomms-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        images: 'stephgl/project-getcomms-api:latest'
        
    # Desplegar en Azure App Service la UI
    - name: Deploy UI to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'project-getcomms-ui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_UI }}
        images: 'stephgl/project-getcomms-ui:latest'
