name: Deploy to Azure App Service using Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Log in on Docker Hub
    - name: Docker Hub Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Build and push images to Docker Hub
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push API
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Fulltimeforce.GetComms.API/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/project-getcomms-api:${{ github.sha }}

    - name: Build and push UI
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Fulltimeforce.GetComms.UI/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/project-getcomms-ui:${{ github.sha }}

    # Deploy API image to Azure App Service
    - name: Deploy API to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'project-getcomms-api'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_API }}
        images: 'stephgl/project-getcomms-api:${{ github.sha }}'
        
    # Deploy UI image to Azure App Service
    - name: Deploy UI to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'project-getcomms-ui'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_UI }}
        images: 'stephgl/project-getcomms-ui:${{ github.sha }}'
